export const MSG_TYPE = {
  EXEC_FUNC_IN_BKGND: 'EXEC_FUNC_IN_BKGND',
  UPDATE_USER_SCRIPTS: 'UPDATE_USER_SCRIPTS'
}

export const USER_SCRIPTS = 'USER_SCRIPTS'
export const USER_SCRIPTS_OPTIONS = 'USER_SCRIPTS_OPTIONS'
export const DEFAULT_CONTENT_SCRIPT = 'DEFAULT_CONTENT_SCRIPT'
